### ISSUE TITLE
Sample data for tutorial

### ISSUE THREAD

**Issue by yairhasfari** [mortonne/aperture#14]
Hi,
Is there a way of getting a hold of the tutorial sample data without having a username and password to Vanderbilt? it's pretty hard understanding how to manage my own data without taking a look at how it should look.
Thanks!
Yair Hasfari

**Comment by mortonne** [comment]
I've replaced the old download link with a link to the data on Dropbox. You should have access now. I've also updated the tutorial. I made a couple code fixes that are relevant for the tutorial, so update the code before trying that.

**Comment by mortonne** [comment]
I've also added a new function, create_exp, which can make setting up an experiment struct to import new data easier in some cases. See the [EEGLAB](https://github.com/mortonne/aperture/wiki/EEGLAB) page for details.

**Comment by yairhasfari** [comment]
Hi Neal,
Thank you very much.
Yair Hasfari

בתאריך 6 בספט׳ 2017 7:35 אחה״צ,‏ "Neal W Morton" <notifications@github.com>
כתב:
